---
- name: Instala pacotes de dependencia do sistema operacional
  apt:
    name: "{{ item }}"
    state: present
  become: yes  
  loop:
    - python-mysqldb
    - mysql-server-5.6

- name: Cria o banco MySQL
  mysql_db: 
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
    
- name: Cria o usuario do MySQL database
  mysql_user:
    login_user: root
    name: "{{ wp_user_name }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  loop:
    - "{{ wp_host_ip }}"

- name: Configura MySQL para aceitar conexões remotas
  copy:
    src: 'files/mysql.cnf'
    dest: '/etc/mysql/my.cnf'
    become: yes
  notify:
    - restart mysql